[[services]]
name = "backend"
source = "backend"

[services.backend.build]
buildCommand = "npm ci --omit=dev && npm run build && npx prisma generate"

[services.backend.deploy]
startCommand = "npx prisma db push --accept-data-loss && npm start"
