[build]
builder = "NIXPACKS"

[deploy]
startCommand = "prisma migrate deploy && node dist/index.js"
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"

[[services]]
name = "planix-backend"
source = "backend"

[services.planix-backend.build]
buildCommand = "npm install --legacy-peer-deps && npm run build"

[services.planix-backend.deploy]
startCommand = "prisma migrate deploy && node dist/index.js"
